version: '3.7'
services:
  stream:
    container_name: rtmp
    image:  rtmp-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1935:1935
      - 8080:8080
    volumes:
      - ./players:/usr/local/nginx/html/players
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/mp4s